name = "main"
description = "Ada example for SDL2"
version = "0.1.0-dev"

authors = ["Alexander F. Rødseth"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["xyproto", "simonjwright"]
licenses = "BSD-3-Clause"
website = ""
tags = ["sdl2", "ada", "example"]

executables = ["main"]
project-files = ["main.gpr"]

[[depends-on]]
sdlada = "^2.0.0"
