module SDL
  module Hint
    FRAMEBUFFER_ACCELERATION           = LibSDL::HINT_FRAMEBUFFER_ACCELERATION
    RENDER_DRIVER                      = LibSDL::HINT_RENDER_DRIVER
    RENDER_OPENGL_SHADERS              = LibSDL::HINT_RENDER_OPENGL_SHADERS
    RENDER_DIRECT3D_THREADSAFE         = LibSDL::HINT_RENDER_DIRECT3D_THREADSAFE
    RENDER_SCALE_QUALITY               = LibSDL::HINT_RENDER_SCALE_QUALITY
    RENDER_VSYNC                       = LibSDL::HINT_RENDER_VSYNC
    VIDEO_ALLOW_SCREENSAVER            = LibSDL::HINT_VIDEO_ALLOW_SCREENSAVER
    VIDEO_X11_XVIDMODE                 = LibSDL::HINT_VIDEO_X11_XVIDMODE
    VIDEO_X11_XINERAMA                 = LibSDL::HINT_VIDEO_X11_XINERAMA
    VIDEO_X11_XRANDR                   = LibSDL::HINT_VIDEO_X11_XRANDR
    GRAB_KEYBOARD                      = LibSDL::HINT_GRAB_KEYBOARD
    MOUSE_RELATIVE_MODE_WARP           = LibSDL::HINT_MOUSE_RELATIVE_MODE_WARP
    VIDEO_MINIMIZE_ON_FOCUS_LOSS       = LibSDL::HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS
    IDLE_TIMER_DISABLED                = LibSDL::HINT_IDLE_TIMER_DISABLED
    ORIENTATIONS                       = LibSDL::HINT_ORIENTATIONS
    ACCELEROMETER_AS_JOYSTICK          = LibSDL::HINT_ACCELEROMETER_AS_JOYSTICK
    XINPUT_ENABLED                     = LibSDL::HINT_XINPUT_ENABLED
    GAMECONTROLLERCONFIG               = LibSDL::HINT_GAMECONTROLLERCONFIG
    JOYSTICK_ALLOW_BACKGROUND_EVENTS   = LibSDL::HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS
    ALLOW_TOPMOST                      = LibSDL::HINT_ALLOW_TOPMOST
    TIMER_RESOLUTION                   = LibSDL::HINT_TIMER_RESOLUTION
    VIDEO_HIGHDPI_DISABLED             = LibSDL::HINT_VIDEO_HIGHDPI_DISABLED
    MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK = LibSDL::HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK
    VIDEO_WIN_D3DCOMPILER              = LibSDL::HINT_VIDEO_WIN_D3DCOMPILER
    VIDEO_WINDOW_SHARE_PIXEL_FORMAT    = LibSDL::HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT
    VIDEO_MAC_FULLSCREEN_SPACES        = LibSDL::HINT_VIDEO_MAC_FULLSCREEN_SPACES
  end

  def self.set_hint(name, value)
    ret = LibSDL.set_hint(name, value.to_s)
    raise Error.new("SDL_SetHint") if ret == 0
  end
end
