' Gambas module file

Private hWindow As Window
Private hTimer As Timer
Private hImage As Image

Public Sub Main()

  hWindow = New Window As "MainWindow"
  With hWindow
    .Resize(620, 387)
    .Resizable = False
    .FrameRate = 60
    .Title = "Hello World!"
    .Show
  End With

  hImage = Image.Load(Application.Dir &/ "../img/grumpy-cat.bmp")

  hTimer = New Timer As "QuitTimer"
  With hTimer
    .Delay = 2000
    .Enabled = True
  End With
End

Public Sub MainWindow_Draw()
  Draw.Clear
  Draw.Image(hImage, 0, 0, 620, 387)
End

Public Sub QuitTimer_Timer()
  hTimer.Enabled = False
  hWindow.Close()
  Quit
End
