name: assembly-examples

on:
  push:
    branches:
    - '*'
    paths:
      - assembly/**
  pull_request:
    branches:
    - '*'
    paths:
      - assembly/**
  workflow_dispatch:

jobs:
  make:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests_list:
        - { folder: "assembly/linux-x86_64" }
    steps:
      - uses: actions/checkout@v4
      - name: install_dependencies
        run: |
          sudo apt update
          sudo apt install -y gnupg libgmp-dev libsdl2-dev libsdl2-image-dev nasm ninja-build
      - name: build
        run: |
              cd ${{ matrix.tests_list.folder }}
              make all
