name: c-examples

on:
  push:
    branches:
    - '*'
    paths:
      - c1*/**
      - c2*/**
      - c8*/**
      - c9*/**
  pull_request:
    branches:
    - '*'
    paths:
      - c1*/**
      - c2*/**
      - c8*/**
      - c9*/**
  workflow_dispatch:

jobs:
  make:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests_list:
        - { folder: "c89" }
        - { folder: "c99" }
        - { folder: "c11" }
        - { folder: "c18" }
        - { folder: "c2x" }
    steps:
      - uses: actions/checkout@v4
      - name: install_dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake curl gnupg libgmp-dev libsdl2-dev libsdl2-image-dev nasm ninja-build
      - name: build
        run: |
              cd ${{ matrix.tests_list.folder }}
              make all
